### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hannesa2** [ViroCommunity/virocore#15]
A lot of changes were made with release pipeline, eg #11 
Please can you create a new tag (not a release !) to see how it's working and to adjust afterwords the `README.md`

**Comment by doranteseduardo** [comment]
Done!

**Comment by hannesa2** [comment]
Thank you.
I figured out, that the `pom` is empty

https://jitpack.io/com/github/ViroCommunity/virocore/rc-1.20.0/virocore-rc-1.20.0.pom

And there is no `aar` included, but there is a `jar`
https://jitpack.io/com/github/ViroCommunity/virocore/rc-1.20.0/

<img width="226" alt="image" src="https://user-images.githubusercontent.com/3314607/132288701-9dd3533a-0cf6-4bf8-879b-5bf60312eaef.png">

 I have to have a look into this issue

**Comment by hannesa2** [comment]
#20 solves it. But there is much more to do
