### ISSUE TITLE
library "libviro_arcore.so" not found

### ISSUE THREAD

**Issue by toffalori** [ViroCommunity/virocore#74]
## Environment
Please provide the following information about your environment:
1. OS: Mac
2. Version: Tried with rc-1.20.1 & rc-1.20.2
3. Device(s): Samsung Galaxy S20 Plus

## Description
I created a new android project and added the .aar file as dependency. When I try to initialize ViroCore I get the following error message: 
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libviro_arcore.so" not found`

This is the gradle file:
```gradle
plugins {
    id 'com.android.application'
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "com.sample.virocoreprototype"
        minSdk 24
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation files('libs/virocore-release.aar')
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```

**Comment by hannesa2** [comment]
This comes without it
<img width="476" alt="image" src="https://user-images.githubusercontent.com/3314607/155701274-03fde3ed-47f3-428e-a4f9-74ec990cc738.png">

but this comes with it
<img width="612" alt="image" src="https://user-images.githubusercontent.com/3314607/155701336-98550f58-4ad2-412a-81fc-ae8f681e8dd0.png">

I guess you need `viroar.aar` as well

**Comment by toffalori** [comment]
Thank you. It looks like it worked. At least I don`t get this error message anymore. But when I create a new ViroViewARCore I get the following error message and he screen remains black. 

```
Didn't create default family (most likely, non-Minikin build)
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.viro.core.internal.font.FontFamily$Font com.viro.core.internal.font.FontFamily.getFont(boolean, int)' on a null object reference
        at com.viro.core.internal.font.SystemFontLoader.init(SystemFontLoader.java:164)
        at com.viro.core.internal.PlatformUtil.<init>(PlatformUtil.java:132)
        at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:551)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:461)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:433)
```

**Comment by toffalori** [comment]
Update: I have just seen that the demo project also shows this error message, but it still works. So there must be something else and I hope I can figure it out myself. For now this issue can be closed :) 

Thank again.

**Comment by hannesa2** [comment]
Please reopen, if it still exists or when you needs assistance
